# Generated by Django 3.1.7 on 2021-04-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ticket_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='detalle',
            field=models.JSONField(default={}),
        ),
    ]
