# Generated by Django 3.1.7 on 2021-04-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210410_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
